---
- name: check for a boot config file
  stat:
    path: /boot/config.txt
  register: boot_config_stat

- name: enable dwc2 driver in boot config
  lineinfile:
    path: /boot/config.txt
    create: no
    line: dtoverlay=dwc2
  when: boot_config_stat.stat.exists

- name: check for an /etc/modules file
  stat:
    path: /etc/modules
  register: etc_modules_stat

- name: enable dwc2 driver in modules
  lineinfile:
    path: /etc/modules
    create: no
    line: dwc2
  when: etc_modules_stat.stat.exists

- name: create /opt/tinypilot-privileged/ path
  file:
    path: /opt/tinypilot-privileged
    state: directory
    mode: '0755'

- name: check for a init-usb-gadget file
  stat:
    path: "{{ init_usb_gadget_path }}"
  register: init_usb_gadget_stat

- name: move usb-gadget initializer
  command: "mv {{ init_usb_gadget_path }} {{ final_init_usb_gadget_path }}"
  when: init_usb_gadget_stat.stat.exists

- name: force mode 700 on init-usb-gadget
  file:
    path: "{{ final_init_usb_gadget_path }}"
    owner: root
    group: root
    mode: '0700'

- name: install usb-gadget initializer as a service
  template:
    src: usb-gadget.systemd.j2
    dest: /lib/systemd/system/usb-gadget.service
    owner: root
    group: root
    mode: '0644'

- name: enable systemd usb-gadget initializer service file
  systemd:
    name: usb-gadget
    enabled: yes
